version: "3.9" 
services:
  kip-profile:
    depends_on:
      - 'kip-profile-mongo'
    
      
    container_name: "kip-profile"
    image: kip-profile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - LOGSTASH_URL=http://localhost:8080
      - MONGODB_CONNECTION_STRING=mongodb://localhost:27018
      - DB_NAME=kip_profile_db
      - COLLECTION_NAME=profiles
    ports:
      - 5000:80
      - 5001:81
      
    build:
      context: .
      dockerfile: Dockerfile
      network: kip-profile

  kip-profile-mongo:
    restart: always
    image: 'mongo'
    container_name: kip-profile-mongo
    ports:
      - '27018:27017'
    build:
        context: .
        dockerfile: Dockerfile
        network: kip-profile
      
